export const ADD_ANNOUNCEMENT = "ADD_ANNOUNCEMENT";
export const EDIT_ANNOUNCEMENT = "EDIT_ANNOUNCEMENT";
export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT";
export const FETCH_ANNOUNCEMENTS = "FETCH_ANNOUNCEMENTS";
export const UPDATE_LIKE_COUNTER = "UPDATE_LIKE_COUNTER";
